name: Main

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Test changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v24
        with:
          path: repositories
          dir_names: true
          include_all_old_new_renamed_files: true

      - name: List all changed files
        run: |
          echo ${{ steps.changed-files.outputs.all_changed_and_modified_files }}
          for file in ${{ steps.changed-files.outputs.all_changed_and_modified_files }}; do
            echo "$file was changed"
          done
          for file in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$file was changed"
          done

      - name: Run changed-files with dir_names
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v24
        with:
          files: |
            repositories/**
          dir_names: "true"

      - name: List all changed files
        run: |
          for dir in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
            echo "$dir was changed"
          done
          for dir in ${{ steps.changed-files.outputs.added_files }}; do
            echo "$dir was changed"
          done