name: Main

on: [push]

jobs:
  changed-files:
    runs-on: ubuntu-latest  # windows-latest | macos-latest
    name: Get changed-files
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 2  # OR "2" -> To retrieve the preceding commit.

      - name: Get changed files
        id: changed-files-dir-names
        uses: tj-actions/changed-files@v24
        with:
          files: |
            repositories/**
          dir_names: true
          include_all_old_new_renamed_files: true

      - name: List all changed files
        run: |
          echo ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}
          for file in ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }}; do
            echo "$file was changed"
          done
          for file in ${{ steps.changed-files-dir-names.outputs.added_files }}; do
            echo "$file was changed"
          done

      - id: set-matrix
        run: echo "::set-output name=directories::$(echo ${{ steps.changed-files-dir-names.outputs.all_changed_and_modified_files }} | jq -R 'split(" ")' | tr -d '\n ')"
    outputs:
      directories: ${{ steps.set-matrix.outputs.directories }}

  plan:
    needs: changed-files
    runs-on: ubuntu-latest
    strategy:
      matrix:
        directory: ${{ fromJson(needs.changed-files.outputs.directories) }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.5
      - name: Set tf plan filename
        id: tf-plan-filename
        run: echo "::set-output name=TF_PLAN::$(echo ${{ matrix.directory }} | tr "/" "-").plan"
      - name: Terraform init and plan
        run: |
          cd ${{ matrix.directory }}
          terraform init
          terraform plan -no-color -out ${{ steps.tf-plan-filename.outputs.TF_PLAN }}
      - name: Archive terraform state artifacts
        uses: actions/upload-artifact@v3
        with:
          name: terraform-plan
          path: |
            ${{ matrix.directory }}/${{ steps.tf-plan-filename.outputs.TF_PLAN }}
          retention-days: 5
  apply:
    needs: [changed-files, plan]
    runs-on: ubuntu-latest
    environment: production
    strategy:
      matrix:
        directory: ${{ fromJson(needs.changed-files.outputs.directories) }}
    steps:
      - uses: actions/checkout@v3
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.5
      - name: Set tf plan filename
        id: tf-plan-filename
        run: echo "::set-output name=TF_PLAN::$(echo ${{ matrix.directory }} | tr "/" "-").plan"
      - name: Download a single artifact
        uses: actions/download-artifact@v3
        with:
          name: terraform-plan
      - name: Terraform apply
        run: |
          export GITHUB_TOKEN=${{ secrets.FLIGH_DECK_GITHUB_TOKEN }}
          mv ${{ steps.tf-plan-filename.outputs.TF_PLAN }} ${{ matrix.directory }}
          cd ${{ matrix.directory }}
          terraform init
          terraform apply -auto-approve "${{ steps.tf-plan-filename.outputs.TF_PLAN }}"
